openapi: 3.0.0
info:
  title: API Unarranged-accounts-overdraft - Open Banking Brasil
  description: |
    API de informações de operações de adiantamento a depositantes do Open Banking Brasil – Fase 2.
    API que retorna informações de operações de crédito do tipo adiantamento a depositantes mantidas nas instituições transmissoras por seus clientes, incluindo dados como denominação, modalidade, número do contrato, tarifas, prazo, prestações, pagamentos, amortizações, garantias, encargos e taxas de juros remuneratórios.\
    Não possui segregação entre pessoa natural e pessoa jurídica.\
    Requer consentimento do cliente para todos os `endpoints`.

    # Permissions necessárias para a API Unarranged-accounts-overdraft

    Para cada um dos paths desta API, além dos escopos (`scopes`) indicados existem `permissions` que deverão ser observadas:

    ### `/contracts`
      - permissions:
        - GET: **UNARRANGED_ACCOUNTS_OVERDRAFT_READ**
    ### `/contracts/{contractId}`
      - permissions: **UNARRANGED_ACCOUNTS_OVERDRAFT_READ**
    ### `/contracts/{contractId}/warranties`
      - permissions:
        - GET: **UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ**
    ### `/contracts/{contractId}/scheduled-instalments`
      - permissions:
        - GET: **UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ**
    ### `/contracts/{contractId}/payments`
      - permissions:
        - GET: **UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ**
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  contact:
    name: Governança do Open Banking Brasil – Interfaces
    email: gt-interfaces@openbankingbr.org
    url: 'https://openbanking-brasil.github.io/areadesenvolvedor/'
servers:
  - url: 'https://api.banco.com.br/open-banking/unarranged-accounts-overdraft/v1'
    description: Servidor de Produção
  - url: 'https://apih.banco.com.br/open-banking/unarranged-accounts-overdraft/v1'
    description: Servidor de Homologação
tags:
  - name: Unarranged Accounts Overdraft
paths:
  /contracts:
    get:
      tags:
        - Unarranged Accounts Overdraft
      summary: Obtém a lista de contratos de adiantamento a depositantes consentidos pelo cliente.
      description: Método para obter a lista de contratos de adiantamento a depositantes mantidos pelo cliente na instituição transmissora e para os quais ele tenha fornecido consentimento.
      operationId: getContracts
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/xFapiAuthDate'
        - $ref: '#/components/parameters/xFapiCustomerIpAddress'
        - $ref: '#/components/parameters/xFapiInteractionId'
        - $ref: '#/components/parameters/xCustomerUserAgent'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftContractList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftContractList'
      security:
        - OpenId:
            - openId
            - unarranged-accounts-overdraft
  /contracts/{contractId}:
    get:
      tags:
        - Unarranged Accounts Overdraft
      summary: Obtém os dados do contrato de adiantamento a depositantes identificado por contractId
      description: Método para obter os dados do contrato de adiantamento a depositantes identificado por contractId mantido pelo cliente na instituição transmissora
      operationId: getContractsContractId
      parameters:
        - $ref: '#/components/parameters/contractId'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/xFapiAuthDate'
        - $ref: '#/components/parameters/xFapiCustomerIpAddress'
        - $ref: '#/components/parameters/xFapiInteractionId'
        - $ref: '#/components/parameters/xCustomerUserAgent'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftContract'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftContract'
      security:
        - OpenId:
            - openId
            - unarranged-accounts-overdraft
  /contracts/{contractId}/warranties:
    get:
      tags:
        - Unarranged Accounts Overdraft
      summary: Obtém a lista de garantias vinculadas ao contrato de adiantamento a depositantes identificado por contractId
      description: Método para obter a lista de garantias vinculadas ao contrato de adiantamento a depositantes identificado por contractId mantido pelo cliente na instituição transmissora
      operationId: getContractsContractIdWarranties
      parameters:
        - $ref: '#/components/parameters/contractId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/xFapiAuthDate'
        - $ref: '#/components/parameters/xFapiCustomerIpAddress'
        - $ref: '#/components/parameters/xFapiInteractionId'
        - $ref: '#/components/parameters/xCustomerUserAgent'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftWarranties'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftWarranties'
      security:
        - OpenId:
            - openId
            - unarranged-accounts-overdraft
  /contracts/{contractId}/scheduled-instalments:
    get:
      tags:
        - Unarranged Accounts Overdraft
      summary: Obtém os dados do cronograma de parcelas do contrato de adiantamento a depositantes identificado por contractId
      description: Método para obter os dados do cronograma de parcelas do contrato de adiantamento a depositantes identificado por contractId mantido pelo cliente na instituição transmissora
      operationId: getContractsContractIdScheduledInstalments
      parameters:
        - $ref: '#/components/parameters/contractId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/xFapiAuthDate'
        - $ref: '#/components/parameters/xFapiCustomerIpAddress'
        - $ref: '#/components/parameters/xFapiInteractionId'
        - $ref: '#/components/parameters/xCustomerUserAgent'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftInstalments'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftInstalments'
      security:
        - OpenId:
            - openId
            - unarranged-accounts-overdraft
  /contracts/{contractId}/payments:
    get:
      tags:
        - Unarranged Accounts Overdraft
      summary: Obtém os dados de pagamentos do contrato de adiantamento a depositantes identificado por contractId
      description: Método para obter os dados de pagamentos do contrato de adiantamento a depositantes identificado por contractId mantido pelo cliente na instituição transmissora
      operationId: getContractsContractIdPayments
      parameters:
        - $ref: '#/components/parameters/contractId'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/xFapiAuthDate'
        - $ref: '#/components/parameters/xFapiCustomerIpAddress'
        - $ref: '#/components/parameters/xFapiInteractionId'
        - $ref: '#/components/parameters/xCustomerUserAgent'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftPayments'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseUnarrangedAccountOverdraftPayments'
      security:
        - OpenId:
            - openId
            - unarranged-accounts-overdraft
components:
  schemas:
    ResponseUnarrangedAccountOverdraftContract:
      $ref: ./schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftContract.yaml
    ResponseUnarrangedAccountOverdraftContractList:
      $ref: ./schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftContractList.yaml
    ResponseUnarrangedAccountOverdraftInstalments:
      $ref: ./schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftInstalments.yaml
    ResponseUnarrangedAccountOverdraftPayments:
      $ref: ./schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftPayments.yaml
    ResponseUnarrangedAccountOverdraftWarranties:
      $ref: ./schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftWarranties.yaml
    productType:
      $ref: ./schemas/enum/EnumUnarrangedAccountOverdraftProductType.yaml
    productSubType:
      $ref: ./schemas/enum/EnumUnarrangedAccountOverdraftSubProductType.yaml
  parameters:
    Authorization:
      $ref: ./parameters/Authorization.yaml
    contractId:
      $ref: ./parameters/ContractId.yaml
    page:
      $ref: ./parameters/Page.yaml
    pageSize:
      $ref: ./parameters/PageSize.yaml
    xCustomerUserAgent:
      $ref: ./parameters/XCustomerUserAgent.yaml
    xFapiAuthDate:
      $ref: ./parameters/XFapiAuthDate.yaml
    xFapiCustomerIpAddress:
      $ref: ./parameters/XFapiCustomerIpAddress.yaml
    xFapiInteractionId:
      $ref: ./parameters/XFapiInteractionId.yaml
  securitySchemes:
    OpenId:
      type: openIdConnect
      openIdConnectUrl: 'https://authserver.example/.well-known/openid-configuration'
  responses:
    OKResponseUnarrangedAccountOverdraftContractList:
      description: Lista de contratos obtida com sucesso.
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: ./headers/XFapiInteractionId.yaml
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseUnarrangedAccountOverdraftContractList'
    OKResponseUnarrangedAccountOverdraftContract:
      description: Dados do contrato de adiantamento a depositantes identificado por contractId
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: ./headers/XFapiInteractionId.yaml
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseUnarrangedAccountOverdraftContract'
    OKResponseUnarrangedAccountOverdraftWarranties:
      description: Lista de garantias vinculadas ao contrato de adiantamento a depositantes identificado por contractId
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: ./headers/XFapiInteractionId.yaml
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseUnarrangedAccountOverdraftWarranties'
    OKResponseUnarrangedAccountOverdraftInstalments:
      description: Dados do cronograma de parcelas do contrato de adiantamento a depositantes identificado por contractId
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: ./headers/XFapiInteractionId.yaml
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseUnarrangedAccountOverdraftInstalments'
    OKResponseUnarrangedAccountOverdraftPayments:
      description: Dados de pagamentos do contrato de adiantamento a depositantes identificado por contractId
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: ./headers/XFapiInteractionId.yaml
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseUnarrangedAccountOverdraftPayments'
    BadRequest:
      $ref: ./responses/BadRequest.yaml
    Forbidden:
      $ref: ./responses/Forbidden.yaml
    InternalServerError:
      $ref: ./responses/InternalServerError.yaml
    MethodNotAllowed:
      $ref: ./responses/MethodNotAllowed.yaml
    NotAcceptable:
      $ref: ./responses/NotAcceptable.yaml
    NotFound:
      $ref: ./responses/NotFound.yaml
    TooManyRequests:
      $ref: ./responses/TooManyRequests.yaml
    Unauthorized:
      $ref: ./responses/Unauthorized.yaml